### ISSUE TITLE
PDF schematics?

### ISSUE THREAD

**Issue by ianrrees** [adafruit/Adafruit-Feather-M0-Express-PCB#1]
Hello!  It would be great if there were a pdf(?) of the schematic here, for folks who don't have Eagle installed for whatever reason.  I'm a KiCad user, and can't quite read the schematic in [this manual](https://cdn-learn.adafruit.com/downloads/pdf/adafruit-feather-m0-express-designed-for-circuit-python-circuitpython.pdf).

I would be glad to make a PR that adds a PDF if that would be accepted?

**Comment by ladyada** [comment]
schematic here :)
https://learn.adafruit.com/bluefruit-nrf52-feather-learning-guide/arduino-bsp-setup?view=all#schematic

**Comment by ianrrees** [comment]
Thanks for the quick response!  That schematic is for a different board, but I think I can figure out what I wanted to know from the photos anyways (or just be patient and wait for mine to arrive...).  Looking forward to experimenting with micropython!

**Comment by caternuson** [comment]
Check out the 'Downloads' page for a given product's guide. That's where most of this stuff tries to live.

https://learn.adafruit.com/adafruit-feather-m0-express-designed-for-circuit-python-circuitpython/downloads#schematic-and-fabrication-print

**Comment by ladyada** [comment]
thanks - that was the right link! we have a lot of feathers :)
