### ISSUE TITLE
Feater M0 Express out of the Box on Win8, no USB Mass Storage in bootmode

### ISSUE THREAD

**Issue by mindforger** [adafruit/Adafruit-Feather-M0-Express-PCB#2]
I followed the guide, plugged it in, without any hub, double pressed the reset button and now its fading the red LED on and off and a new COM Port is showing in the drivers, but no mass storage device. What is wrong with that? I can not load UF2s.

I can not even flash a bootloader, there is only an UF2 Version on the page, pretty much useless for me if i can not access the bootloader.

**Comment by ladyada** [comment]
please post in the adafruit forums under circuitpython thx!

**Comment by mindforger** [comment]
i just want to let you know that this sounds a bit bold to me and that i want to make clear **i do not want** to register with the forum 
sure this is not the exactly right place to deal with a bootloader issue as this repo is for the PCB mostly, but the bootloader is hosted here and i can not use it as it is UF2 format only, which i cn not load with SWD programmer
