### ISSUE TITLE
LICENSE.txt not in repo

### ISSUE THREAD

**Issue by biomurph** [adafruit/Adafruit-Feather-M0-Express-PCB#4]
Hi Adafruit,

I am looking around at how OSH companies are licensing their products, and i notice that you say that you license under CC-SA, and in the readme you reference a file called LICENSE.txt that is not included in the repo. Looking at a handful of other repos, this seems to be the case across the board. 

Can you update your files with an actual license for us to follow?

**Comment by ladyada** [comment]
its cc sa by, use wahtevers on cc website plz
